### PR TITLE
Lab Work

### PR DESCRIPTION
**Pull request by AwsomeStar123456**
This pull request is to merge our completed lab work into main.

### CODE REVIEW

**Review by shem-snow — APPROVED** [review]
Not bad. Not bad at all.

My name is Shem and I approve this pull request.

**Comment by AwsomeStar123456** [comment]
Ayman when you get time can you review this pull request?

**Review by aymanhab1b — APPROVED** [review]

**Comment by aymanhab1b** [comment]
All okay.

**Comment by aymanhab1b** [comment]
Hi Semrah,

Sorry for the delay, I was feeling a bit under the weather this weekend.

Regards,
Ayman

From: Semrah Odobasic ***@***.***>
Date: Monday, September 16, 2024 at 9:07 AM
To: uofu-emb/2024-lab01-Semrah-Odobasic-Logan-Allen ***@***.***>
Cc: Mohammedayman Habib ***@***.***>, Review requested ***@***.***>
Subject: Re: [uofu-emb/2024-lab01-Semrah-Odobasic-Logan-Allen] Lab Work (PR #1)

Ayman when you get time can you review this pull request?

**Pull request merged**
